name:                haskvelle
version:             0.1.0.0
github:              "HiiGHoVuTi/haskvelle"
license:             BSD3
author:              "Maxime"
maintainer:          "emixampons@gmail.com"
copyright:           "2021 Maxime"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HiiGHoVuTi/haskvelle#readme>

dependencies:
- base >= 4.7 && < 5
- structured-cli
- data-default
- directory
- process
- turtle
- configurator
- pretty-simple
- text
- unordered-containers
- hs-duktape
- bytestring
- aeson
- time

library:
  source-dirs: src

executables:
  haskvelle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2
    dependencies:
    - haskvelle

tests:
  haskvelle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskvelle
